title: Hello, world! I'm Onuoha Obinna
description: > # this means to ignore newlines until "baseurl:"
  "A collection of my works and the thoughts that run through my mind as I learn to code. all things data science"
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: "Onuoha Obinna" # add your name
author-img: "onuoha-obinna.jpg" # add your photo
about-author: "A budding data scientist, being enormously helped by the internet." # add description
social-twitter: "onuoha_data" # add your Twitter handle
social-facebook: "onuohasilver" # add your Facebook handle
social-github: "onuohasilver" # add your Github handle
social-linkedin: "obinna-onuoha-85ab10158" # add your Linkedin handle
social-email: "onuohasilver9@gmail.com"# add your Email address

# Disqus
discus-identifier: onuohasilver # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
