# General Settings
name: Onuoha Obinna
job_title: Machine learning student
email: onuohasilver9@gmail.com
description: I'm a graduate computer engineer with interest in machine learning. I work with computers.
avatar: /assets/pics/acarril-princeton.jpg
favicon: /assets/icon/analytics-trans.png
twitter_handler: onuohadata
disqus: onuohasilver

# Social Accounts
social_networks:
-  { name: facebook, url: 'http://facebook.com/onuohasilver' }
-  { name: twitter, url: 'http://twitter.com/onuohadata' }
-  { name: instagram, url: 'https://www.instagram.com/onuohasilver/' }
-  { name: google-plus, url: '' }
-  { name: linkedin, url: 'http://linkedin.com/obinna-onuoha-85ab10158' }
-  { name: skype, url: '' }
-  { name: github, url: 'https://github.com/onuohasilver' }
-  { name: codepen, url: '' }
-  { name: stack-overflow, url: '' }
-  { name: dribbble, url: '' }
-  { name: behance, url: '' }
-  { name: pinterest, url: '' }
-  { name: tumblr, url: '' }
-  { name: youtube, url: '' }
-  { name: vimeo, url: '' }
-  { name: vine, url: '' }
-  { name: 500px, url: '' }
-  { name: flickr, url: '' }
-  { name: spotify, url: '' }
-  { name: steam, url: '' }
-  { name: wordpress, url: '' }
-  { name: xing, url: '' }
-  { name: bitcoin, url: '' }
-  { name: pocket, url: '' }
-  { name: applemusic, url: '' }

# Modules Settings
show_categories: 1
show_tags: 1
show_email: 1
show_rss: 1
show_comments: 1
show_menu: 1
fixed_sidebar: 1

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: "true"

# Serving
url: ""
baseurl: ""

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------
collections:
  projects:
    output: true
    permalink: /projects/:path/
  research:
    output: true
    permalink: /research/:title

defaults:
  - scope:
      path: ""
      type: "research"
    values:
      layout: research

# Includes
include: ["_pages"]

# Outputting
permalink: /posts/:title
category_dir: categories

# Pagination
paginate: 10
paginate_path: "/page:num/"

# Conversion
markdown: kramdown
excerpt_separator: <!--more-->

# Assets Settings
sass:
  sass_dir: assets/partials
  style: compressed

# Fixes (bundle exec error)
exclude: [vendor]

# Syntax highlighting
highlighter: rouge

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
#    css_class: 'highlight'
